In [1]:
import logging
import warnings
warnings.showwarning = lambda *args, **kwargs: None
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', -1)
import matplotlib.pyplot as plt
from datetime import datetime
from azureml.core import Experiment, Workspace, Dataset
from azureml.train.automl import AutoMLConfig

# Setting Up The Workspace and Experiment

In [2]:
import azureml.core

experiment_name = 'AutomatedML-TimeSeriesForecasting'
ws = Workspace.from_config()
experiment = Experiment(ws, experiment_name)
output = {}
output['SDK version'] = azureml.core.VERSION
output['Subsciption ID'] = ws.subscription_id
output['Workspace'] = ws.name
output['Resource Group'] = ws.resource_group
output['Location'] = ws.location
output['Run History'] = experiment_name
output_df = pd.DataFrame(data = output, index = [''])
output_df.T

SDK version     1.57.0
Subsciption ID  0c19fc19-85fd-4aa4-b133-61dd20fa93df
Workspace       auotml-example-workspace
Resource Group  edwin.spartan117-rg
Location        southeastasia
Run History     AutomatedML-TimeSeriesForecasting

# Setting Up The Compute Target

In [3]:
from azureml.core.compute import ComputeTarget, AmlCompute
from azureml.core.compute_target import ComputeTargetException

cluster_name = 'AutoML-Cluster'

try:
    compute_target = ComputeTarget(workspace = ws, name = cluster_name)
    print('Using an existing compute cluster')
except ComputeTargetException:
    compute_config = AmlCompute.provisioning_configuration(vm_size = 'Standard_Ds12_v2', max_nodes = 4)
    compute_target = ComputeTarget.create(ws, cluster_name, compute_config)
    
print('Checking cluster status...')
compute_target.wait_for_completion(show_output = True, timeout_in_minutes = 20)

Using an existing compute cluster
Checking cluster status...
Succeeded
AmlCompute wait for completion finished

Minimum number of nodes requested have been provisioned

# Data Preparation

In [4]:
time_column = 'timeStamp'
target_column = 'demand'

nyc_energy = Dataset.Tabular.from_delimited_files(
    path = 'https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/nyc_energy.csv').with_timestamp_columns(
    fine_grain_timestamp = time_column)
nyc_energy.take(10).to_pandas_dataframe().reset_index(drop = True)

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

            timeStamp  demand  precip   temp
0 2012-01-01 00:00:00  4937.5  0.0     46.13
1 2012-01-01 01:00:00  4752.1  0.0     45.89
2 2012-01-01 02:00:00  4542.6  0.0     45.04
3 2012-01-01 03:00:00  4357.7  0.0     45.03
4 2012-01-01 04:00:00  4275.5  0.0     42.61
5 2012-01-01 05:00:00  4274.7  0.0     39.02
6 2012-01-01 06:00:00  4324.9  0.0     38.78
7 2012-01-01 07:00:00  4350.0  0.0     42.74
8 2012-01-01 08:00:00  4480.9  0.0     38.90
9 2012-01-01 09:00:00  4664.2  0.0     44.67

In [5]:
nyc_energy_data = nyc_energy.time_before(datetime(2017, 8, 10, 5))
nyc_energy_train = nyc_energy_data.time_before(datetime(2017, 8, 8, 5), include_boundary = True)
nyc_energy_train.to_pandas_dataframe().reset_index(drop = True).sort_values(time_column)

nyc_energy_test = nyc_energy_data.time_after(datetime(2017, 8, 8, 6))
nyc_energy_test.to_pandas_dataframe().reset_index(drop = True)

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

             timeStamp    demand  precip   temp
0  2017-08-08 06:00:00  5590.992  0.0000  66.17
1  2017-08-08 07:00:00  6147.033  0.0000  66.29
2  2017-08-08 08:00:00  6592.425  0.0000  66.72
3  2017-08-08 09:00:00  6874.533  0.0000  67.37
4  2017-08-08 10:00:00  7010.542  0.0000  68.30
5  2017-08-08 11:00:00  7078.158  0.0000  68.89
6  2017-08-08 12:00:00  7213.317  0.0000  70.60
7  2017-08-08 13:00:00  7329.750  0.0000  72.83
8  2017-08-08 14:00:00  7426.250  0.0000  73.33
9  2017-08-08 15:00:00  7505.633  0.0000  74.89
10 2017-08-08 16:00:00  7578.192  0.0000  77.90
11 2017-08-08 17:00:00  7548.050  0.0000  79.24
12 2017-08-08 18:00:00  7357.117  0.0000  78.68
13 2017-08-08 19:00:00  7131.433  0.0000  76.80
14 2017-08-08 20:00:00  6986.575  0.0000  74.60
15 2017-08-08 21:00:00  6869.292  0.0000  72.58
16 2017-08-08 22:00:00  6587.058  0.0000  70.67
17 2017-08-08 23:00:00  6194.442  0.0000  69.15
18 2017-08-09 00:00:00  5754.708  0.0000  68.47
19 2017-08-09 01:00:00  5439.667  0.0000  67.74
20 2017-08-09 02:00:00  5195.325  0.0000  67.31
21 2017-08-09 03:00:00  5044.508  0.0000  67.50
22 2017-08-09 04:00:00  5010.000  0.0000  65.22
23 2017-08-09 05:00:00  5195.300  0.0000  64.11
24 2017-08-09 06:00:00  5651.033  0.0000  63.79
25 2017-08-09 07:00:00  6240.392  0.0000  64.28
26 2017-08-09 08:00:00  6774.967  0.0330  66.56
27 2017-08-09 09:00:00  7140.267  0.0000  70.87
28 2017-08-09 10:00:00  7348.917  0.0000  74.92
29 2017-08-09 11:00:00  7516.775  0.0000  78.04
30 2017-08-09 12:00:00  7671.625  0.0000  80.18
31 2017-08-09 13:00:00  7806.833  0.0000  82.01
32 2017-08-09 14:00:00  7949.467  0.0000  82.85
33 2017-08-09 15:00:00  8065.808  0.0000  84.61
34 2017-08-09 16:00:00  8162.875  0.0000  84.20
35 2017-08-09 17:00:00  8136.758  0.0000  84.04
36 2017-08-09 18:00:00  7852.642  0.0000  82.86
37 2017-08-09 19:00:00  7535.067  0.0000  79.66
38 2017-08-09 20:00:00  7360.883  0.0000  76.28
39 2017-08-09 21:00:00  7207.583  0.5815  73.60
40 2017-08-09 22:00:00  6917.650  0.0448  72.26
41 2017-08-09 23:00:00  6487.642  0.4814  71.10
42 2017-08-10 00:00:00  6053.458  0.0030  71.51
43 2017-08-10 01:00:00  5714.258  0.0213  71.06
44 2017-08-10 02:00:00  5497.025  0.0068  71.21
45 2017-08-10 03:00:00  5360.583  0.0070  70.39
46 2017-08-10 04:00:00  5333.775  0.0030  69.18
47 2017-08-10 05:00:00  5534.683  0.0000  68.09

# Configuring The AutoML Task

In [6]:
automl_config = AutoMLConfig(
    task = 'forecasting', primary_metric = 'normalized_root_mean_squared_error', experiment_timeout_hours = 1, 
    training_data = nyc_energy_train, label_column_name = target_column, time_column_name = time_column, max_horizon = 24,
    compute_target = compute_target, enable_early_stopping =  True, n_cross_validations = 3, max_cores_per_iteration = -1,
    max_concurrent_iterations = 3, verbosity = logging.INFO)

experiment_run = experiment.submit(automl_config, show_output = True)

Submitting remote run.
No run_configuration provided, running on AutoML-Cluster with default configuration
Running on remote compute: AutoML-Cluster

Experiment,Id,Type,Status,Details Page,Docs Page
AutomatedML-TimeSeriesForecasting,AutoML_08297ff7-16dd-410a-bc1b-6542dce452c6,automl,NotStarted,Link to Azure Machine Learning studio,Link to Documentation

Current status: DatasetFeaturization. Beginning to featurize the CV split.
Current status: ModelSelection. Beginning model selection.

********************************************************************************************
DATA GUARDRAILS:

TYPE:         Time Series ID detection
STATUS:       PASSED
DESCRIPTION:  The data set was analyzed, and no duplicate time index were detected.
              Learn more about time-series forecasting configurations: https://aka.ms/AutomatedMLForecastingConfiguration

********************************************************************************************

TYPE:         Short series handling
STATUS:       PASSED
DESCRIPTION:  Automated ML detected enough data points for each series in the input data to continue with training.
              Learn more about short series handling: https://aka.ms/AutomatedMLShortSeriesHandling

********************************************************************************************

TYPE:         Frequency detection
STATUS:       PASSED
DESCRIPTION:  The time series was analyzed, all data points are aligned with detected frequency.
              Learn more about data preparation for time-series forecasting: https://aka.ms/AutomatedMLDataPreparation

********************************************************************************************

TYPE:         Missing feature values imputation
STATUS:       DONE
DESCRIPTION:  If the missing values are expected, let the run complete. Otherwise cancel the current run and use a script to customize the handling of missing feature values that may be more appropriate based on the data type and business requirement.
              Learn more about missing value imputation: https://aka.ms/AutomatedMLFeaturization
DETAILS:
+------------------------------+------------------------------+------------------------------+
|Column name                   |Missing value count           |Imputation type               |
+==============================+==============================+==============================+
|precip                        |230                           |median                        |
|temp                          |186                           |median                        |
+------------------------------+------------------------------+------------------------------+

********************************************************************************************

TYPE:         Automatic cross validation
STATUS:       DONE
DESCRIPTION:  Cross validation parameter(s) were automatically set for your dataset.
              Learn more about time-series forecasting configurations: https://aka.ms/AutomatedMLForecastingConfiguration
DETAILS:      If n_cross_validations and/or cv_step_size is not specified, Automated ML will determine those cross validation parameters automatically for you.
+----------------------------------------------------------------+
|Number of periods between two consecutive cross validation folds|
+================================================================+
|24                                                              |
+----------------------------------------------------------------+

********************************************************************************************

********************************************************************************************
ITER: The iteration being evaluated.
PIPELINE: A summary description of the pipeline being evaluated.
DURATION: Time taken for the current iteration.
METRIC: The result of computing score on the fitted pipeline.
BEST: The best observed score thus far.
********************************************************************************************

 ITER   PIPELINE                                       DURATION            METRIC      BEST
    0    Naive                                         0:00:09             0.1210    0.1210
    1    SeasonalNaive                                 0:00:10             0.1213    0.1210
    2    Average                                       0:00:09             0.0905    0.0905
    3    SeasonalAverage                               0:00:09             0.1337    0.0905
    4    ExponentialSmoothing                          0:02:27             0.0821    0.0821
    7   StandardScalerWrapper LightGBM                 0:00:10             0.0439    0.0439
    8   StandardScalerWrapper XGBoostRegressor         0:00:20             0.0464    0.0439
    9   MaxAbsScaler ElasticNet                        0:00:11             0.1172    0.0439
   10   RobustScaler ElasticNet                        0:00:11             0.1163    0.0439
   11   MinMaxScaler ElasticNet                        0:00:11             0.1167    0.0439
   12   StandardScalerWrapper ElasticNet               0:00:11             0.1171    0.0439
   13   MinMaxScaler RandomForest                      0:00:09             0.0593    0.0439
   14   MaxAbsScaler ElasticNet                        0:00:13             0.1181    0.0439
   15   StandardScalerWrapper ElasticNet               0:00:12             0.1171    0.0439
   16   MaxAbsScaler ElasticNet                        0:00:11             0.1174    0.0439
   17   StandardScalerWrapper ElasticNet               0:00:11             0.1168    0.0439
   18   MinMaxScaler ExtremeRandomTrees                0:00:10             0.0637    0.0439
   19   MinMaxScaler RandomForest                      0:00:13             0.0476    0.0439
   20   MinMaxScaler ExtremeRandomTrees                0:00:31             0.0801    0.0439
   21   MinMaxScaler ExtremeRandomTrees                0:00:29             0.1037    0.0439
   22   MaxAbsScaler ExtremeRandomTrees                0:00:30             0.0578    0.0439
   23   MinMaxScaler DecisionTree                      0:00:31             0.0679    0.0439
   24   RobustScaler ExtremeRandomTrees                0:00:29             0.0782    0.0439
   25   MinMaxScaler LightGBM                          0:00:30             0.0548    0.0439
   26   RobustScaler DecisionTree                      0:00:29             0.0583    0.0439
   27   StandardScalerWrapper ExtremeRandomTrees       0:00:30             0.0857    0.0439
   28   StandardScalerWrapper RandomForest             0:00:30             0.0752    0.0439
   29   MinMaxScaler LightGBM                          0:00:30             0.0470    0.0439
   30   RobustScaler RandomForest                      0:00:31             0.0522    0.0439
   31   StandardScalerWrapper RandomForest             0:00:33             0.0481    0.0439
   32   StandardScalerWrapper ExtremeRandomTrees       0:00:33             0.0869    0.0439
   33   StandardScalerWrapper ExtremeRandomTrees       0:00:31             0.0825    0.0439
    5    Arimax                                        0:12:26                nan    0.0439
    6                                                  0:00:00                nan    0.0439
   34   StandardScalerWrapper ExtremeRandomTrees       0:00:29             0.0852    0.0439
ERROR: {
    "additional_properties": {
        "statusCode": 400
    },
    "error": {
        "additional_properties": {
            "debugInfo": null
        },
        "code": "UserError",
        "severity": null,
        "message": "Run AutoML_08297ff7-16dd-410a-bc1b-6542dce452c6_34 already completed",
        "message_format": null,
        "message_parameters": null,
        "reference_code": null,
        "details_uri": null,
        "target": null,
        "details": [],
        "inner_error": null,
        "additional_info": null
    },
    "correlation": {
        "operation": "0fcbc6fe0e4d47cbbe88f5e45f0ce8d4",
        "request": "648966892e4d6891"
    },
    "environment": "southeastasia",
    "location": "southeastasia",
    "time": {},
    "component_name": "CJPBatch"
}
   35    VotingEnsemble                                0:00:47             0.0313    0.0313

In [7]:
best_run, fitted_model = experiment_run.get_output()
fitted_model.steps

[('timeseriestransformer',
  TimeSeriesTransformer(country_or_region=None, drop_column_names=[], featurization_config=FeaturizationConfig(blocked_transformers=None, column_purposes=None, dataset_language=None, prediction_transform_type=None, transformer_params=None), force_time_index_features=None, freq='H', grain_column_names=['_automl_dummy_grain_col'], group=None, lookback_features_removed=False, max_horizon=24, origin_time_colname='origin', pipeline=Pipeline(memory=None, steps=[('unique_target_grain_dropper', UniqueTargetGrainDropper(cv_step_size=24, max_horizon=24, n_cross_validations=3, target_lags=[0], target_rolling_window_size=0)), ('make_numeric_na_dummies', MissingDummiesTransformer(numerical_columns=['precip', 'temp'])), ('impute_na_numeric_datetime', TimeSeriesImputer(end=None, freq='H', impute_by_horizon=False, input_column=['precip', 'temp'], limit=None, limit_direction='forward', method=OrderedDict([('ffill', [])]), option='fillna', order=None, origin=None, value={'precip': 0.0, 'temp': 56.19})), ('grain_dropper', ShortGrainDropper(cv_step_size=24, max_horizon=24, n_cross_validations=3, target_lags=[0], target_rolling_window_size=0)), ('restore_dtypes_transform', RestoreDtypesTransformer(dtypes={'precip': dtype('float64'), '_automl_target_col': dtype('float64'), 'temp': dtype('float64')}, target_column='_automl_target_col')), ('make_categoricals_numeric', NumericalizeTransformer(categories_by_col={}, exclude_columns=set(), include_columns=set())), ('make_time_index_featuers', TimeIndexFeaturizer(correlation_cutoff=0.99, country_or_region=None, datetime_columns=None, force_feature_list=None, freq='H', holiday_end_time=None, holiday_start_time=None, overwrite_columns=True, prune_features=True)), ('make_categoricals_onehot', CategoryBinarizer(columns=[], drop_first=False, dummy_na=False, encode_all_categoricals=False, prefix=None, prefix_sep='_'))], verbose=False), pipeline_type=TimeSeriesPipelineType.FULL, seasonality=24, time_column_name='timeStamp', time_index_non_holiday_features=['_automl_year', '_automl_half', '_automl_quarter', '_automl_month', '_automl_day', '_automl_hour', '_automl_am_pm', '_automl_hour12', '_automl_wday', '_automl_qday', '_automl_week'], use_stl=None)),
 ('prefittedsoftvotingregressor',
  PreFittedSoftVotingRegressor(estimators=[('7', Pipeline(memory=None, steps=[('standardscalerwrapper', StandardScalerWrapper(copy=True, with_mean=False, with_std=False)), ('lightgbmregressor', LightGBMRegressor(min_data_in_leaf=20, n_jobs=-1, problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=None))], verbose=False)), ('29', Pipeline(memory=None, steps=[('minmaxscaler', MinMaxScaler(clip=False, copy=True, feature_range=(0, 1))), ('lightgbmregressor', LightGBMRegressor(boosting_type='gbdt', colsample_bytree=0.8, learning_rate=0.09474210526315789, max_bin=1023, max_depth=8, min_data_in_leaf=0.006300382669981896, min_split_gain=0.05263157894736842, n_estimators=25, n_jobs=-1, num_leaves=7, problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=None, reg_alpha=0.44999999999999996, reg_lambda=0.075, subsample=0.5499999999999999, subsample_freq=9))], verbose=False)), ('0', Pipeline(memory=None, steps=[('naive', Naive(timeseries_param_dict={'time_column_name': 'timeStamp', 'grain_column_names': None, 'target_column_name': 'demand', 'drop_column_names': [], 'overwrite_columns': True, 'dropna': False, 'transform_dictionary': {'min': '_automl_target_col', 'max': '_automl_target_col', 'mean': '_automl_target_col'}, 'max_horizon': 24, 'origin_time_colname': 'origin', 'country_or_region': None, 'n_cross_validations': 3, 'short_series_handling': True, 'max_cores_per_iteration': -1, 'feature_lags': None, 'target_aggregation_function': None, 'cv_step_size': 24, 'seasonality': 24, 'use_stl': None, 'freq': 'H', 'short_series_handling_configuration': 'auto', 'target_lags': [0], 'target_rolling_window_size': 0, 'arimax_raw_columns': ['precip', 'timeStamp', 'temp']}))], verbose=False)), ('4', Pipeline(memory=None, steps=[('exponentialsmoothing', ExponentialSmoothing(timeseries_param_dict={'time_column_name': 'timeStamp', 'grain_column_names': None, 'target_column_name': 'demand', 'drop_column_names': [], 'overwrite_columns': True, 'dropna': False, 'transform_dictionary': {'min': '_automl_target_col', 'max': '_automl_target_col', 'mean': '_automl_target_col'}, 'max_horizon': 24, 'origin_time_colname': 'origin', 'country_or_region': None, 'n_cross_validations': 3, 'short_series_handling': True, 'max_cores_per_iteration': -1, 'feature_lags': None, 'target_aggregation_function': None, 'cv_step_size': 24, 'seasonality': 24, 'use_stl': None, 'freq': 'H', 'short_series_handling_configuration': 'auto', 'target_lags': [0], 'target_rolling_window_size': 0, 'arimax_raw_columns': ['precip', 'timeStamp', 'temp']}))], verbose=False))], weights=[0.5714285714285714, 0.07142857142857142, 0.21428571428571427, 0.14285714285714285]))]

In [8]:
featurization_summary = fitted_model.named_steps['timeseriestransformer'].get_featurization_summary()
pd.DataFrame.from_records(featurization_summary)

,RawFeatureName,TypeDetected,Dropped,EngineeredFeatureCount,Transformations
0,precip,Numeric,No,2,"[MedianImputer, ImputationMarker]"
1,temp,Numeric,No,2,"[MedianImputer, ImputationMarker]"
2,_automl_target_col,Numeric,No,1,[ImputationMarker]
3,timeStamp,DateTime,No,11,[DateTimeTransformer]

# Evaluation of Time Series Forecasting Results

In [9]:
features_test = nyc_energy_test.to_pandas_dataframe().reset_index(drop = True)
demand_test = features_test.pop(target_column).values

demand_forecast, features = fitted_model.forecast(features_test)

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

In [10]:
from common.forecasting_helper import align_outputs
from azureml.automl.runtime.shared.score.scoring import score_regression
from automl.client.core.common import constants

nyc_energy_forecast_df = align_outputs(demand_forecast, features, features_test, demand_test, target_column)

scores = score_regression(nyc_energy_forecast_df['predicted'], nyc_energy_forecast_df[target_column], 
                          list(constants.Metric.SCALAR_REGRESSION_SET), None, None, None)
scores

{'mean_absolute_error': 191.83950881140268,
 'mean_absolute_percentage_error': 2.9332863175222896,
 'normalized_root_mean_squared_error': 0.0873236350686606,
 'normalized_median_absolute_error': 0.04708408790870623,
 'root_mean_squared_log_error': 0.037601983650790656,
 'r2_score': 0.9125591097326048,
 'root_mean_squared_error': 253.62917151927348,
 'normalized_mean_absolute_error': 0.06604967070171981,
 'normalized_root_mean_squared_log_error': 0.08301223040603609,
 'explained_variance': 0.9392659602212606,
 'spearman_correlation': 0.9769865392965696,
 'median_absolute_error': 136.75447888347935}